### PR TITLE
VP1-51 VR Survey Interface

### PR DESCRIPTION
**Pull request by CoreyClements1**
VR survey-taking interface set up. To test, read the README in the interface's folder (everything is contained to the VERA -> UI -> SurveyInterface folder). Currently, survey will start automatically on play for testing purposes, based on a survey given from a scriptable object. Once linked with server-side stuff, this will not be the case.

### CODE REVIEW

**Comment by chloerbeato** [comment]
Feedback
- I would update the README with any dependencies the survey interface has such as the XR rig and how to make it compatible with the survey interface and include instructions on how to set it up in a new scene
- I would have the survey interface’s position starting farther away from the camera

**Review by lamcnguyen89 — APPROVED** [review]
Hi Corey,

The survey works perfectly. It also works in the VLAT menu. However just a suggestion... Make it more clear that the VLAT menu will disappear when filling out a survey.

**Review by lamcnguyen89 — APPROVED** [review]
Hello Corey. It looks good

**Review by chloerbeato — APPROVED** [review]
Tested VR survey functionality and it looks good

**Pull request merged**
