### PR TITLE
Addition of upload notification window

### PR DESCRIPTION
**Pull request by furuyahir**
Had issues rebasing to sign old commits, so squashed them all, signed, submitting as new PR

### CODE REVIEW

**Review by CoreyClements1 — APPROVED** [review]
Previously reviewed, no changes since review (since it's a copy); everything still good.

**Comment by lucidbard** [comment]
Two things -- you have your API key and Study UDID in the scene in the individual component. Probably should delete those. Second, you might want to add the window to the main demo scene, and scale it?

**Review by lucidbard — CHANGES_REQUESTED** [review]
Uploading Notification should be in the main demo scene otherwise it may be missed. We should also think later about integrating it into other canvas inputs.

**Comment by furuyahir** [comment]
Removed key info.
Adding window to main demo scene punted to: https://vera-platform.atlassian.net/browse/VP1-131

**Review by lucidbard — APPROVED** [review]

**Pull request merged**
